const GET_PROPERTY_START = 'GET_PROPERTY_START';
const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS';
const GET_PROPERTY_FAIL = 'GET_PROPERTY_FAIL';

export { GET_PROPERTY_START, GET_PROPERTY_SUCCESS, GET_PROPERTY_FAIL }